### PR TITLE
fix: Make QueryParams extension public

### LINKED ISSUE #41: Add support for alternate date encoding strategies in QueryDecoder.
Currently `QueryDecoder` only supports UTC dates formatted as `yyyy-MM-dd'T'HH:mm:ssZ`. It would be helpful for dates to be represented using alternate formats, such as `secondsSince1970`.

### PR DESCRIPTION
**Pull request by djones6**
#45 contained a mistake where the extension providing the default values for `QueryParams.dateEncodingStrategy` and `dateDecodingStrategy` was not `public`.  This made it a breaking change.

This adjusts the visibility to public, and also adds some documentation that was missing or incomplete.

Resolves #41

### CODE REVIEW

File: Sources/KituraContracts/Contracts.swift [hunk 1]
```diff
@@ -561,12 +565,17 @@ public protocol QueryParams: Codable {
     static var dateEncodingStrategy: JSONEncoder.DateEncodingStrategy { get }
 }
 
-extension QueryParams {
+/// Defines default values for the `dateDecodingStrategy` and `dateEncodingStrategy`. The
+/// default formatting for a `Date` in a `QueryParams` type is defined by `Coder.dateFormatter`,
+/// which uses the "UTC" timezone and "yyyy-MM-dd'T'HH:mm:ssZ" date format.
+public extension QueryParams {
```
Comment (ianpartridge) [inline Sources/KituraContracts/Contracts.swift]: Stylistically, I prefer leaving this as `extension QueryParams` and marking each individual member as `public static var` - that way you can see the access level at a glance without having to look at the top level scope.

File: Sources/KituraContracts/Contracts.swift [hunk 2]
```diff
@@ -561,13 +565,18 @@ public protocol QueryParams: Codable {
...
 
+/// Defines default values for the `dateDecodingStrategy` and `dateEncodingStrategy`. The
+/// default formatting for a `Date` in a `QueryParams` type is defined by `Coder.dateFormatter`,
+/// which uses the "UTC" timezone and "yyyy-MM-dd'T'HH:mm:ssZ" date format.
 extension QueryParams {
 
-    static var dateDecodingStrategy: JSONDecoder.DateDecodingStrategy {
+    /// Default value: `Coder().dateFormatter`
+    public static var dateDecodingStrategy: JSONDecoder.DateDecodingStrategy {
         return .formatted(Coder().dateFormatter)
```
Comment (ianpartridge) [inline Sources/KituraContracts/Contracts.swift]: This creates a new `Coder` every time the property is accessed - is that intentional?

File: Sources/KituraContracts/Contracts.swift [hunk 3]
```diff
@@ -561,14 +565,19 @@ public protocol QueryParams: Codable {
...
 }
 
+/// Defines default values for the `dateDecodingStrategy` and `dateEncodingStrategy`. The
+/// default formatting for a `Date` in a `QueryParams` type is defined by `Coder.dateFormatter`,
+/// which uses the "UTC" timezone and "yyyy-MM-dd'T'HH:mm:ssZ" date format.
 extension QueryParams {
 
-    static var dateDecodingStrategy: JSONDecoder.DateDecodingStrategy {
-        return .formatted(Coder().dateFormatter)
+    /// Default value: `Coder().dateFormatter`
```
Comment (ianpartridge) [inline Sources/KituraContracts/Contracts.swift]: Comments need updating - and below.

**Review by ianpartridge — APPROVED** [review]
